name             'testbed'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures testbed'
long_description 'Installs/Configures testbed'
version          '0.1.0'

depends 'apt'
depends 'xfce4'
depends 'vim'
